// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxdliwfsmavtagwnrjon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4ZGxpd2ZzbWF2dGFnd25yam9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzY2MTMsImV4cCI6MjA1NzgxMjYxM30.sIu1obthEMxkaI4ZjGhbVitJNyCsQsW1BZyWDDffZKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);